# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='powers',
            new_name='speciality',
        ),
    ]
